name: dbt Production Deploy

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'models/**'
      - 'macros/**'
      - 'tests/**'
      - 'seeds/**'
      - 'snapshots/**'
      - 'dbt_project.yml'
      - 'packages.yml'
  workflow_dispatch:

jobs:
  dbt_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-snowflake==1.9.0
      
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          netfilx:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 8
          EOF
      
      - name: Install dbt packages
        run: dbt deps
      
      - name: Run dbt debug
        run: dbt debug
      
      - name: Run dbt seed
        run: dbt seed --target prod
      
      - name: Run dbt snapshots
        run: dbt snapshot --target prod
      
      - name: Run dbt run
        run: dbt run --target prod
      
      - name: Run dbt test
        run: dbt test --target prod
      
      - name: Generate and upload dbt docs
        run: |
          dbt docs generate --target prod
      
      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-production-artifacts
          path: |
            target/manifest.json
            target/catalog.json
            target/run_results.json
            target/index.html
          retention-days: 30
