version: 2

sources:
  - name: netfilx
    database: movielens
    schema: raw
    tables:
      - name: r_movies
        identifier: raw_movies
      - name: r_ratings
        identifier: raw_ratings